### PR TITLE
made a crucial edit to the readme file

### PR DESCRIPTION
**Pull request by orbyfied**
This edit is incredibly important to the project as a whole;
The project is meant to teach people how a professional library or application should work and be documented.
If the documentation is critically off, this is a detrement to the effectiveness of the last two points, especially the second one.

### CODE REVIEW

**Comment by oliver194** [comment]
amazing pull request 😍

**Comment by ImajinDevon** [comment]
This commit was planned to be added in the upcoming commit.

**Comment by oliver194** [comment]
image
glass pringles

**Comment by orbyfied** [comment]
top 10 bruh moments

**Comment by oliver194** [comment]
> 

stealing the credit for yourself

**Pull request closed without merging**
